/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u71744222177
 */
public class JFrmNrcPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmNrcPrincipal() {
        initComponents();
        setTitle("Sistema de mercadinho da Nureen");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuNrcCadastros = new javax.swing.JMenu();
        jMnuNrcUsuarios = new javax.swing.JMenuItem();
        jMnuNrcClientes = new javax.swing.JMenuItem();
        jMnuNrcVendedores = new javax.swing.JMenuItem();
        jMnuNrcFornecedores = new javax.swing.JMenuItem();
        jMnuNrcProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuNrcSair = new javax.swing.JMenuItem();
        jMnuNrcMovimentos = new javax.swing.JMenu();
        jMnuNrcVendas = new javax.swing.JMenuItem();
        jMnuNrcCompras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuNrcCadastros.setMnemonic('c');
        jMnuNrcCadastros.setText("Cadastros");

        jMnuNrcUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuNrcUsuarios.setMnemonic('u');
        jMnuNrcUsuarios.setText("Usuários");
        jMnuNrcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcUsuariosActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcUsuarios);

        jMnuNrcClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuNrcClientes.setText("Clientes");
        jMnuNrcClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcClientesActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcClientes);

        jMnuNrcVendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedorcerto.png"))); // NOI18N
        jMnuNrcVendedores.setMnemonic('v');
        jMnuNrcVendedores.setText("Vendedores");
        jMnuNrcVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcVendedoresActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcVendedores);

        jMnuNrcFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedornv.png"))); // NOI18N
        jMnuNrcFornecedores.setMnemonic('f');
        jMnuNrcFornecedores.setText("Fornecedores");
        jMnuNrcFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcFornecedoresActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcFornecedores);

        jMnuNrcProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuNrcProdutos.setMnemonic('p');
        jMnuNrcProdutos.setText("Produtos");
        jMnuNrcProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcProdutosActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcProdutos);
        jMnuNrcCadastros.add(jSeparator1);

        jMnuNrcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuNrcSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuNrcSair.setMnemonic('s');
        jMnuNrcSair.setText("Sair");
        jMnuNrcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcSairActionPerformed(evt);
            }
        });
        jMnuNrcCadastros.add(jMnuNrcSair);

        jMenuBar1.add(jMnuNrcCadastros);

        jMnuNrcMovimentos.setMnemonic('m');
        jMnuNrcMovimentos.setText("Movimentos");

        jMnuNrcVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMnuNrcVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuNrcVendas.setText("Vendas");
        jMnuNrcVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuNrcVendasActionPerformed(evt);
            }
        });
        jMnuNrcMovimentos.add(jMnuNrcVendas);

        jMnuNrcCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMnuNrcCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuNrcCompras.setText("Compras");
        jMnuNrcMovimentos.add(jMnuNrcCompras);

        jMenuBar1.add(jMnuNrcMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuNrcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgNrcUsuarios jDlgMpvUsuarios = new JDlgNrcUsuarios(null, true);
        jDlgMpvUsuarios.setVisible(true);
        setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMnuNrcUsuariosActionPerformed

    private void jMnuNrcVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuNrcVendasActionPerformed

    private void jMnuNrcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuNrcSairActionPerformed

    private void jMnuNrcVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcVendedoresActionPerformed
        // TODO add your handling code here:
        JDlgNrcVendedores jDlgNrcVendedores = new JDlgNrcVendedores(null, true);
        jDlgNrcVendedores.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMnuNrcVendedoresActionPerformed

    private void jMnuNrcClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcClientesActionPerformed
        // TODO add your handling code here:
        JDlgNrcClientes jDlgNrcClientes = new JDlgNrcClientes(null, true);
        jDlgNrcClientes.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMnuNrcClientesActionPerformed

    private void jMnuNrcFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcFornecedoresActionPerformed
        // TODO add your handling code here:
        JDlgNrcFornecedores jDlgNrcFornecedores = new JDlgNrcFornecedores(null, true);
        jDlgNrcFornecedores.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMnuNrcFornecedoresActionPerformed

    private void jMnuNrcProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuNrcProdutosActionPerformed
        // TODO add your handling code here:
        JDlgNrcProdutos jDlgNrcProdutos = new JDlgNrcProdutos(null, true);
        jDlgNrcProdutos.setVisible(true);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jMnuNrcProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmNrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmNrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmNrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmNrcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmNrcPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuNrcCadastros;
    private javax.swing.JMenuItem jMnuNrcClientes;
    private javax.swing.JMenuItem jMnuNrcCompras;
    private javax.swing.JMenuItem jMnuNrcFornecedores;
    private javax.swing.JMenu jMnuNrcMovimentos;
    private javax.swing.JMenuItem jMnuNrcProdutos;
    private javax.swing.JMenuItem jMnuNrcSair;
    private javax.swing.JMenuItem jMnuNrcUsuarios;
    private javax.swing.JMenuItem jMnuNrcVendas;
    private javax.swing.JMenuItem jMnuNrcVendedores;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
